# Generated by Django 5.1 on 2024-08-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcingapp', '0002_news_delete_parcing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published_at',
        ),
    ]
